version: 0.2

phases:
  build:
    commands:
      - echo "Performing Git operations"
      - git clone https://github.com/subhomayb/app-test.git
      - cd app-test
      - git remote add codecommit https://git-codecommit.us-west-1.amazonaws.com/v1/repos/cicd-github
      - git push codecommit master

artifacts:
  files: '**/*'

